site_name: locfilm
site_description: Project to find locations for filming
repo_url: https://github.com/Locfilm/locfilm-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/Locfilm">Locfilm</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
    - Locations: 'api/locations.md'
    - Bookings: 'api/bookings.md'
